server.port: 8081

appliances:
  - name: IM
    id: 555d9a6ce4b0d37c827d4029
    host: im

endpoints:
  - name: IM
    legacyId: 1
    id: 555d9a6fe4b0d37c827d402d
    serviceType: INCIDENT_MANAGEMENT
    port: 50040
    username: admin
    password: netwitness
    secure: true
    applianceId: 555d9a6ce4b0d37c827d4029
    version: 10.6.0.0.867

security:
  auth:
    server.url: https://localhost/api/auth/login